COMMAND_NAME=$@
ENHANCER_LIB=`realpath ../../build/librepeater.so`
OUR_DIR=`pwd`

echo "Verifying command ${COMMAND_NAME}"

ENHANCER_NONINTRUSIVE=1 ENHANCER_SCREENSHOT=${OUR_DIR}/identity.bmp ENHANCER_EXIT_AFTER=20 LD_PRELOAD=${ENHANCER_LIB} ${COMMAND_NAME}
ENHANCER_NOW=1 ENHANCER_CAMERAID=0 ENHANCER_ANGLE=1 ENHANCER_DISTANCE=1 ENHANCER_SCREENSHOT=${OUR_DIR}/identityVerify.bmp ENHANCER_EXIT_AFTER=20 LD_PRELOAD=${ENHANCER_LIB} ${COMMAND_NAME}
